import json
import asyncio
import os
import sys
from typing import List, Dict, Any

# Ensure we can import from app
sys.path.append(os.getcwd())

from app.api.chat_phase4 import chat_endpoint
from app.models.schemas import ChatRequest, ContactInfo
from app.services.lead_handler import LEAD_SESSIONS

def score_response(response: str, expected_keywords: List[str]) -> float:
    if not response:
        return 0.0
    score = 0
    for word in expected_keywords:
        if word.lower() in response.lower():
            score += 1
    return score / len(expected_keywords)

async def run_evaluation():
    print("🚀 Starting Product Validation Suite...")
    
    with open("scripts/test_queries.json", "r") as f:
        test_queries = json.load(f)
    
    results = []
    
    # 1. KNOWLEDGE & BUSINESS RULE TESTS
    for test in test_queries:
        query = test["query"]
        expected = test["expect"]
        test_type = test["type"]
        
        # Reset session for clean test
        session_id = f"test_{test_type}_{query[:10]}"
        if session_id in LEAD_SESSIONS:
            del LEAD_SESSIONS[session_id]
            
        request = ChatRequest(
            query=query,
            context={"session_id": session_id}
        )
        
        response = await chat_endpoint(request)
        answer = response.get("answer") or response.get("message", "")
        confidence = response.get("confidence", 0.0)
        
        score = score_response(answer, expected)
        status = "PASS" if score >= 0.5 else "FAIL"
        
        # Special check for fees rule
        if test_type == "business_rule" and "fee" in query.lower():
            if "Fee structures vary" in answer:
                status = "PASS"
            else:
                status = "FAIL"
        
        results.append({
            "query": query,
            "type": test_type,
            "score": score,
            "confidence": confidence,
            "status": status,
            "answer_preview": answer[:100] + "..."
        })
        print(f"[{status}] Query: {query} | Score: {score} | Conf: {confidence}")

    # 2. LEAD GATE MULTI-TURN TEST
    print("\n🧐 Testing Lead Gate (2-turn flow)...")
    gate_session = "gate_test_session"
    if gate_session in LEAD_SESSIONS:
        del LEAD_SESSIONS[gate_session]
        
    # Turn 1: General query (should allow)
    res1 = await chat_endpoint(ChatRequest(query="What is AIMS?", context={"session_id": gate_session}))
    res1_ans = res1.get("answer") or ""
    # Smart check: Turn 1 is OK if it provides an answer AND does not start with a rejection
    turn1_ok = res1_ans and not res1_ans.strip().startswith(("Please enter", "That email", "I'd love to help with that! Before we continue"))
    
    # Turn 2: Follow up (should trigger gate)
    res2 = await chat_endpoint(ChatRequest(query="Tell me about MBA", context={"session_id": gate_session}))
    gate_msg = res2.get("answer") or ""
    # Acceptance criteria: Either the invitation or a validation error (since Turn 2 is not a valid lead string)
    gate_triggered = (
        "provide your: **name, email, and course**" in gate_msg.lower() or 
        "please enter your full name" in gate_msg.lower() or
        "email doesn't look right" in gate_msg.lower()
    )
    
    if not gate_triggered:
        print(f"DEBUG: Turn 2 unexpected answer: {gate_msg}")
    
    gate_status = "PASS" if (turn1_ok and gate_triggered) else "FAIL"
    print(f"[{gate_status}] Lead Gate Test")

    # 3. GENERATE REPORT
    report_md = f"""# Product Validation Report

## Executive Summary
- **Overall Accuracy**: {sum(r['score'] for r in results if r['type']=='knowledge') / 4:.2%}
- **Business Rules (Fees)**: {"✅ PASS" if results[-1]['status'] == 'PASS' else "❌ FAIL"}
- **Lead Gate Persistence**: {"✅ PASS" if gate_status == 'PASS' else "❌ FAIL"}

## Detailed Results

| Query | Type | Score | Confidence | Status |
|-------|------|-------|------------|--------|
"""
    for r in results:
        report_md += f"| {r['query']} | {r['type']} | {r['score']:.2f} | {r['confidence']:.2f} | {r['status']} |\n"

    report_md += f"""
## Multi-Turn Behavior
- **Turn 1 (General)**: {"Allowed" if turn1_ok else "Blocked (Unexpected)"}
- **Turn 2 (Gated)**: {"Gate Triggered" if gate_triggered else "Gate Failed to Trigger"}

---
## Full Responses (Debug Logs)
"""
    for r in results:
        report_md += f"### Query: {r['query']}\n**Answer**: {r['answer_preview']}\n\n"

    report_md += f"""
---
*Generated by Product Validation Suite v1.0*
"""
    
    with open("validation_report.md", "w") as f:
        f.write(report_md)
        
    print("\n✅ Validation complete! Report saved to validation_report.md")

if __name__ == "__main__":
    asyncio.run(run_evaluation())
